$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1447837966629.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8c61e7e1250340ab9ccb09e0218e13ad",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"46a8f669f64c4ccc8e722ee51cb8a6e5",
          "label":"home",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":472},
            "size":{
              "width":320,
              "height":96},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd70e9bd08e447bcb9e5e9d486828dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":472},
                "size":{
                  "width":320,
                  "height":96},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/regen/home_u0.png"}},
{
          "id":"a95906ff57c945ad82ed880f2f8900ea",
          "label":"dpiPhoneScreen",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":472}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 dpiPhoneScreen 到 Next 向左滑动 out 250ms 向左滑动 in 250ms",
                      "panelsToStates":[{
                          "panelPath":["a95906ff57c945ad82ed880f2f8900ea"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":250},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":250},
                              "compress":false}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 dpiPhoneScreen 到 Previous 向右滑动 out 250ms 向右滑动 in 250ms",
                      "panelsToStates":[{
                          "panelPath":["a95906ff57c945ad82ed880f2f8900ea"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideRight",
                                "duration":250},
                              "animateIn":{
                                "easing":"slideRight",
                                "duration":250},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8e01f4cbe6f5476193d30574b9b10917",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"47f95cb30ca44e46bec9228558f3a8a4",
                  "label":"home1",
                  "parentDynamicPanel":"a95906ff57c945ad82ed880f2f8900ea",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":472},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11dadc82880a4b9b8d8606970d4c77a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a95906ff57c945ad82ed880f2f8900ea",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":472},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主页/regen/home1_u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"91a4c17d546c4055b44a69c4d7002f6e",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"46c1e8aabaca457296a8cd9d0eb514c0",
                  "label":"home2",
                  "parentDynamicPanel":"a95906ff57c945ad82ed880f2f8900ea",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":472},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2d0befd161f4dc0a246d5574b18c982",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a95906ff57c945ad82ed880f2f8900ea",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":472},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主页/regen/home2_u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"4f49fceda8d5447bb5554356b224cf64",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fa8a021b1cf94117b8f39ec66ffe8f1c",
                  "label":"home3",
                  "parentDynamicPanel":"a95906ff57c945ad82ed880f2f8900ea",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":472},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c5409598f11489891973e124a68ae13",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a95906ff57c945ad82ed880f2f8900ea",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":472},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/主页/regen/home3_u7.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "46a8f669f64c4ccc8e722ee51cb8a6e5":{
      "scriptId":"u0"},
    "dd70e9bd08e447bcb9e5e9d486828dfb":{
      "scriptId":"u1"},
    "a95906ff57c945ad82ed880f2f8900ea":{
      "scriptId":"u2"},
    "47f95cb30ca44e46bec9228558f3a8a4":{
      "scriptId":"u3"},
    "11dadc82880a4b9b8d8606970d4c77a9":{
      "scriptId":"u4"},
    "46c1e8aabaca457296a8cd9d0eb514c0":{
      "scriptId":"u5"},
    "a2d0befd161f4dc0a246d5574b18c982":{
      "scriptId":"u6"},
    "fa8a021b1cf94117b8f39ec66ffe8f1c":{
      "scriptId":"u7"},
    "1c5409598f11489891973e124a68ae13":{
      "scriptId":"u8"}}});